services:
  - type: web
    name: kohai-metabase
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_CONNECTION_URI
        sync: false
      - key: PORT
        value: 3000
      - key: MB_JETTY_PORT
        value: 3000
      - key: JAVA_TIMEZONE
        value: UTC
